#include <string.h>
#include <stdio.h>

const char* academicInfoCode = "4Y114630";
const char* md5 = "267e46685fd99bd731a68314618975d3";
const short int lastByte = 0xD3;

void functionTaskA(char* data) {
	char buffer[211];
	buffer[0] = '\0';
	strcpy(buffer, data);

	if (strcmp(buffer, "my_super_secret_sentence") == 0) {
		printf("Access Granted\n");
	}
	else {
		printf("Access Denied");
	}
}

int main()
{
	//functionTaskA((char*)"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\xEF\xBE\xAD\xDE");
	/*4Y114630 -> 4630 -> 0x34363330 */
	functionTaskA((char*)("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\x30\x33\x36\x34"));
	/*functionTaskA((char*)"AAAAAAAAAAAAAAAAAAAAA");*/
	return 0;
}
